name: Simple Input Example

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Enter a message"
        required: true

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print user message
        run: echo "You said:${{ github.event.inputs.message }}"
